// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCV43Z4V5t2ApE8eyoBsDATqxM9K_ZtSWI',
    appId: '1:482521515396:android:2acd7d9dd5385af24f09d1',
    messagingSenderId: '482521515396',
    projectId: 'persona-navi',
    storageBucket: 'persona-navi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBa8bmfhIK-D-Nc2gAYfeMv1rIPeyUyEIQ',
    appId: '1:482521515396:ios:085398f4a6292a8b4f09d1',
    messagingSenderId: '482521515396',
    projectId: 'persona-navi',
    storageBucket: 'persona-navi.firebasestorage.app',
    iosClientId: '482521515396-i1kpdqc3e1chu5slkikphiurpj3u1hna.apps.googleusercontent.com',
    iosBundleId: 'com.personanavigator.personaNavigator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBa8bmfhIK-D-Nc2gAYfeMv1rIPeyUyEIQ',
    appId: '1:482521515396:ios:085398f4a6292a8b4f09d1',
    messagingSenderId: '482521515396',
    projectId: 'persona-navi',
    storageBucket: 'persona-navi.firebasestorage.app',
    iosClientId: '482521515396-i1kpdqc3e1chu5slkikphiurpj3u1hna.apps.googleusercontent.com',
    iosBundleId: 'com.personanavigator.personaNavigator',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBo_ZL6iAd7kAydyC1ya939g1mikcLLj8E',
    appId: '1:482521515396:web:4f24770712112fc94f09d1',
    messagingSenderId: '482521515396',
    projectId: 'persona-navi',
    authDomain: 'persona-navi.firebaseapp.com',
    storageBucket: 'persona-navi.firebasestorage.app',
    measurementId: 'G-Z5ETEB5S1Z',
  );
}
